# ticker 
okx:
  parameter:
    - ts
    - open24h
    - last
    - high24h
    - low24h
    - last
    - vol24h

gateio:
  parameter:
    - time_ms
    - last
    - last
    - high_24h
    - low_24h
    - highest_bid
    - base_volume
    - change_percentage

bybit:
  parameter:
    - ts
    - lastPrice
    - lastPrice
    - highPrice24h
    - lowPrice24h
    - prevPrice24h
    - volume24h
    - price24hPcnt



upbit:
  parameter:
    - timestamp
    - opening_price
    - trade_price
    - high_price
    - low_price
    - prev_closing_price
    - acc_trade_volume_24h
    - signed_change_price
    - signed_change_rate

bithumb:
  parameter:
    - timestamp
    - opening_price
    - trade_price
    - high_price
    - low_price
    - prev_closing_price
    - acc_trade_volume_24h
    - signed_change_price
    - signed_change_rate


coinone:
  parameter:
    - timestamp
    - first
    - last
    - high
    - low
    - yesterday_last
    - target_volume

korbit:
  parameter:
    - timestamp
    - open
    - close   
    - high
    - low
    - prevClose
    - volume
    - priceChange
    - priceChangePercent


binance:
  parameter:
    - E
    - o
    - c
    - h
    - l
    - x
    - v
    - p
    - P

kraken:
  parameter:
    - last
    - ask
    - high
    - low
    - last
    - volume
    - change
    - change_pct
