okx:
  parameter:
    - open24h
    - last
    - high24h
    - low24h
    - last
    - vol24h

gateio:
  parameter:
    - last
    - last
    - high_24h
    - low_24h
    - highest_bid
    - base_volume

bybit:
  parameter:
    - lastPrice
    - lastPrice
    - highPrice24h
    - lowPrice24h
    - prevPrice24h
    - volume24h
